sudo: required
language: java
jdk:
  - oraclejdk9

services:
  - docker

env:
  global:
  - CONTAINER_NAME=rpses
  
script:
  - export TAG=`if [ "${TRAVIS_BRANCH}" == "master" ]; then echo "latest"; else echo ${TRAVIS_BRANCH} ; fi`
  - docker build -t ${CONTAINER_NAME} .

after_success:
  - docker login -u AWS -p ${AWS_REGISTRY_PW} https://${AWS_ACCOUNT_ID}.dkr.ecr.eu-central-1.amazonaws.com
  - docker tag ${CONTAINER_NAME}:latest ${AWS_ACCOUNT_ID}.dkr.ecr.eu-central-1.amazonaws.com/${CONTAINER_NAME}:${TAG}
  - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.eu-central-1.amazonaws.com/${CONTAINER_NAME}:${TAG}
